# Generated by Django 2.2.4 on 2024-01-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='favorite_books',
            field=models.ManyToManyField(to='app1.Books'),
        ),
    ]
