# Generated by Django 2.2.4 on 2024-01-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20240118_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='desc',
            new_name='description',
        ),
    ]
